### ISSUE TITLE
Example project doesn't work out of the box

### ISSUE THREAD

**Issue by weyert** [fabrix-app/spool-sequelize#26]
#### Issue Description
If you checkout the project found at https://github.com/fabrix-app/example-app it's not working due the incorrect `index.ts` for the `config`-directory which doesn't import the `models.ts` file which stops Sequelize from being loaded.

#### Environment
- node version: lts
- fabrix version: latest
- operating system: MacOS 10.14.2

**Comment by scott-wyatt** [comment]
Spool-sequelize should throw error if the spool is loaded and config/models or config/stores is not.

**Comment by weyert** [comment]
It's not doing that for me in the example app
