### ISSUE TITLE
bug(): Replicators

### ISSUE THREAD

**Issue by scott-wyatt** [fabrix-app/spool-sequelize#47]
Currently, spool-sequelize breaks when trying to use read/write replication from sequelize core.
- [ ] Should allow connection via Replicators
- [ ] Should fall back to default config when replicators not defined.

**Comment by jaumard** [comment]
look like you already tried but didn't give any stack trace or errors, shame :p ^^ 
Should we close it ? Or do you still have the code to give it a round ?

**Comment by scott-wyatt** [comment]
Its really old from when I didn’t think it worked lol, it was do I didn’t forget lol. There’s no code or stack traces. I was just trouble shooting a different app.
