### ISSUE TITLE
feat(): Allow Read/Write Replicators in config/store

### ISSUE THREAD

**Issue by scott-wyatt** [fabrix-app/spool-sequelize#49]
### Branch v1.6
https://github.com/fabrix-app/spool-sequelize/blob/v1.6/lib/transformer.ts

#### Feature Description
Sequelize allows for [Read Replicators](https://sequelize.org/master/manual/read-replication.html) to be configured.  Spool-sequelize is not respecting this configuration.  

The desired configuration should follow the config/stores guidelines and look sort of like:

```js
// config/stores

export const store = {
nameOfStore: {
    orm: 'sequelize',
    logging: process.env.POSTGRES_LOGGING || false,
    dialect: 'postgres',
    migrate: process.env.DATABASE_MIGRATE || 'drop',
    plugins: {
      // views: require('sequelize-views-support'),
      // hierarchy: require('sequelize-hierarchy')
    },
    // Should by default look for replication property first, else fallback to normal configuration
    replication: {
      read: [
         { host: '8.8.8.8', username: 'read-username', password: 'some-password' },
         { host: '9.9.9.9', username: 'another-username', password: null }
      ],
      write: {
        host: '1.1.1.1',
        username: 'write-username',
        password: 'any-password'
      }
  },
}

```

- [ ] Should by default use the replicators if configured
- [ ] Should fallback to using the normal config if not
- [ ] Should test read/write replicators in Intergration Tests
- [ ] Should test replicators config in Unit Tests 

#### Related
#47

**Comment by jaumard** [comment]
> Should by default use the replicators if configured
  Should fallback to using the normal config if not

not sure that's how replicator works, your should give Sequelize the default connexion information who are becoming the default information of the replicators (to avoid to have to duplicate info on all entries). So my idea here is that the normal config will work as default information for the replicators. So all information on the config file are given to Sequelize, and sequelize is doing his job of merging them :) less stuff to code and maintain later that way. 

What do you think ?

**Comment by scott-wyatt** [comment]
Probably a good idea!

**Comment by jaumard** [comment]
From the look of the code, this kind of config should already work ^^ there is nothing to do :D 
```
      storeoverride: {
        migrate: 'drop',
        orm: 'sequelize',
        database: 'Sequelize',
        host: '127.0.0.1',
        dialect: 'postgres',
        replication: {
          read: [
            { username: 'read-username', password: 'some-password' },
            { username: 'another-username', password: null, database: 'Sequelize2', }
          ],
          write: {
            username: 'write-username',
            password: 'any-password'
          }
        },
      },
```
Unfortunately I can't test or run any test as they need postgresql so I need to do the setup first. 
I'll try to do that during the week to confirm it works :) and add tests for the future

**Comment by scott-wyatt** [comment]
So I thought so too, but I think there is some place in the transformer that is constructing which uri to use for the database and doesn't take into account the rest of the config, I could be wrong.

**Comment by jaumard** [comment]
Sequelize can take a `uri` or an object to describe the connection, so basically both are directly pass to Sequelize constructor, so if there is replica, sequelize will take uri or the object as default params for all the replica. So we should be good :) if there any problem I'll gladly fix bugs around that :) just asign them to me
