### ISSUE TITLE
feat(): Upgrade to Sequelize 6

### ISSUE THREAD

**Issue by scott-wyatt** [fabrix-app/spool-sequelize#50]
### Branch v1.7
https://github.com/fabrix-app/spool-sequelize/blob/v1.7/lib/transformer.ts

This has been started, but is currently not passing any tests.

#### Issue Description
Sequelize version 5 has been out for a while and 6 is now released. It fixes many of the security issues for v4. to get us onto version 6, we first need to migrate to version 5, and then do the small adjustments to get to version 6.  

A good place to start would be with [this migration guide for migrating from 4 to 5](https://sequelize.org/v5/manual/upgrade-to-v5.html).

- [ ] should upgrade to Sequelize version 6 and higher.
- [ ] should make PR to master or v1.6

#### Related
#49 #46

**Comment by jaumard** [comment]
Sequelize 6 is not release yet, it's still in beta. So it's mainly a migration to 5 and preparation to 6. Changes are quite important but they will mostly be visible in SQL request so I guess in Services. I'll start by #49 first and finish with this one as it will a bit longer to do :)

**Comment by scott-wyatt** [comment]
Sounds good!
